<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/twitter-bootstrap/css/bootstrap.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/twitter-bootstrap/css/bootstrap-responsive.css">
  </head>
  <body>
	  <div class="container">
          <?php echo $this->layout()->content; ?>
	  </div>		
  </body>	
</html>  